services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-app-hardik
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/basic
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpass
    networks:
      - mysql_default
networks:
  mysql_default:
    external: true
